#SingleInstance Force
; Generated by komorebic.exe

Start(ffm) {
    Run, komorebic.exe start  --ffm %ffm%, , Hide
}

Stop() {
    Run, komorebic.exe stop, , Hide
}

State() {
    Run, komorebic.exe state, , Hide
}

Query(state_query) {
    Run, komorebic.exe query %state_query%, , Hide
}

Subscribe(named_pipe) {
    Run, komorebic.exe subscribe %named_pipe%, , Hide
}

Unsubscribe(named_pipe) {
    Run, komorebic.exe unsubscribe %named_pipe%, , Hide
}

Log() {
    Run, komorebic.exe log, , Hide
}

QuickSaveResize() {
    Run, komorebic.exe quick-save-resize, , Hide
}

QuickLoadResize() {
    Run, komorebic.exe quick-load-resize, , Hide
}

SaveResize(path) {
    Run, komorebic.exe save-resize %path%, , Hide
}

LoadResize(path) {
    Run, komorebic.exe load-resize %path%, , Hide
}

Focus(operation_direction) {
    Run, komorebic.exe focus %operation_direction%, , Hide
}

Move(operation_direction) {
    Run, komorebic.exe move %operation_direction%, , Hide
}

CycleFocus(cycle_direction) {
    Run, komorebic.exe cycle-focus %cycle_direction%, , Hide
}

CycleMove(cycle_direction) {
    Run, komorebic.exe cycle-move %cycle_direction%, , Hide
}

Stack(operation_direction) {
    Run, komorebic.exe stack %operation_direction%, , Hide
}

Resize(edge, sizing) {
    Run, komorebic.exe resize %edge% %sizing%, , Hide
}

ResizeAxis(axis, sizing) {
    Run, komorebic.exe resize-axis %axis% %sizing%, , Hide
}

Unstack() {
    Run, komorebic.exe unstack, , Hide
}

CycleStack(cycle_direction) {
    Run, komorebic.exe cycle-stack %cycle_direction%, , Hide
}

MoveToMonitor(target) {
    Run, komorebic.exe move-to-monitor %target%, , Hide
}

MoveToWorkspace(target) {
    Run, komorebic.exe move-to-workspace %target%, , Hide
}

SendToMonitor(target) {
    Run, komorebic.exe send-to-monitor %target%, , Hide
}

SendToWorkspace(target) {
    Run, komorebic.exe send-to-workspace %target%, , Hide
}

SendToMonitorWorkspace(target_monitor, target_workspace) {
    Run, komorebic.exe send-to-monitor-workspace %target_monitor% %target_workspace%, , Hide
}

FocusMonitor(target) {
    Run, komorebic.exe focus-monitor %target%, , Hide
}

FocusWorkspace(target) {
    Run, komorebic.exe focus-workspace %target%, , Hide
}

FocusMonitorWorkspace(target_monitor, target_workspace) {
    Run, komorebic.exe focus-monitor-workspace %target_monitor% %target_workspace%, , Hide
}

CycleMonitor(cycle_direction) {
    Run, komorebic.exe cycle-monitor %cycle_direction%, , Hide
}

CycleWorkspace(cycle_direction) {
    Run, komorebic.exe cycle-workspace %cycle_direction%, , Hide
}

MoveWorkspaceToMonitor(target) {
    Run, komorebic.exe move-workspace-to-monitor %target%, , Hide
}

NewWorkspace() {
    Run, komorebic.exe new-workspace, , Hide
}

ResizeDelta(pixels) {
    Run, komorebic.exe resize-delta %pixels%, , Hide
}

InvisibleBorders(left, top, right, bottom) {
    Run, komorebic.exe invisible-borders %left% %top% %right% %bottom%, , Hide
}

WorkAreaOffset(left, top, right, bottom) {
    Run, komorebic.exe work-area-offset %left% %top% %right% %bottom%, , Hide
}

AdjustContainerPadding(sizing, adjustment) {
    Run, komorebic.exe adjust-container-padding %sizing% %adjustment%, , Hide
}

AdjustWorkspacePadding(sizing, adjustment) {
    Run, komorebic.exe adjust-workspace-padding %sizing% %adjustment%, , Hide
}

ChangeLayout(default_layout) {
    Run, komorebic.exe change-layout %default_layout%, , Hide
}

LoadCustomLayout(path) {
    Run, komorebic.exe load-custom-layout %path%, , Hide
}

FlipLayout(axis) {
    Run, komorebic.exe flip-layout %axis%, , Hide
}

Promote() {
    Run, komorebic.exe promote, , Hide
}

Retile() {
    Run, komorebic.exe retile, , Hide
}

EnsureWorkspaces(monitor, workspace_count) {
    Run, komorebic.exe ensure-workspaces %monitor% %workspace_count%, , Hide
}

ContainerPadding(monitor, workspace, size) {
    Run, komorebic.exe container-padding %monitor% %workspace% %size%, , Hide
}

WorkspacePadding(monitor, workspace, size) {
    Run, komorebic.exe workspace-padding %monitor% %workspace% %size%, , Hide
}

WorkspaceLayout(monitor, workspace, value) {
    Run, komorebic.exe workspace-layout %monitor% %workspace% %value%, , Hide
}

WorkspaceCustomLayout(monitor, workspace, path) {
    Run, komorebic.exe workspace-custom-layout %monitor% %workspace% %path%, , Hide
}

WorkspaceLayoutRule(monitor, workspace, at_container_count, layout) {
    Run, komorebic.exe workspace-layout-rule %monitor% %workspace% %at_container_count% %layout%, , Hide
}

WorkspaceCustomLayoutRule(monitor, workspace, at_container_count, path) {
    Run, komorebic.exe workspace-custom-layout-rule %monitor% %workspace% %at_container_count% %path%, , Hide
}

ClearWorkspaceLayoutRules(monitor, workspace) {
    Run, komorebic.exe clear-workspace-layout-rules %monitor% %workspace%, , Hide
}

WorkspaceTiling(monitor, workspace, value) {
    Run, komorebic.exe workspace-tiling %monitor% %workspace% %value%, , Hide
}

WorkspaceName(monitor, workspace, value) {
    Run, komorebic.exe workspace-name %monitor% %workspace% %value%, , Hide
}

ToggleWindowContainerBehaviour() {
    Run, komorebic.exe toggle-window-container-behaviour, , Hide
}

TogglePause() {
    Run, komorebic.exe toggle-pause, , Hide
}

ToggleTiling() {
    Run, komorebic.exe toggle-tiling, , Hide
}

ToggleFloat() {
    Run, komorebic.exe toggle-float, , Hide
}

ToggleMonocle() {
    Run, komorebic.exe toggle-monocle, , Hide
}

ToggleMaximize() {
    Run, komorebic.exe toggle-maximize, , Hide
}

RestoreWindows() {
    Run, komorebic.exe restore-windows, , Hide
}

Manage() {
    Run, komorebic.exe manage, , Hide
}

Unmanage() {
    Run, komorebic.exe unmanage, , Hide
}

ReloadConfiguration() {
    Run, komorebic.exe reload-configuration, , Hide
}

WatchConfiguration(boolean_state) {
    Run, komorebic.exe watch-configuration %boolean_state%, , Hide
}

WindowHidingBehaviour(hiding_behaviour) {
    Run, komorebic.exe window-hiding-behaviour %hiding_behaviour%, , Hide
}

CrossMonitorMoveBehaviour(move_behaviour) {
    Run, komorebic.exe cross-monitor-move-behaviour %move_behaviour%, , Hide
}

ToggleCrossMonitorMoveBehaviour() {
    Run, komorebic.exe toggle-cross-monitor-move-behaviour, , Hide
}

UnmanagedWindowOperationBehaviour(operation_behaviour) {
    Run, komorebic.exe unmanaged-window-operation-behaviour %operation_behaviour%, , Hide
}

FloatRule(identifier, id) {
    Run, komorebic.exe float-rule %identifier% "%id%", , Hide
}

ManageRule(identifier, id) {
    Run, komorebic.exe manage-rule %identifier% "%id%", , Hide
}

WorkspaceRule(identifier, id, monitor, workspace) {
    Run, komorebic.exe workspace-rule %identifier% "%id%" %monitor% %workspace%, , Hide
}

IdentifyObjectNameChangeApplication(identifier, id) {
    Run, komorebic.exe identify-object-name-change-application %identifier% "%id%", , Hide
}

IdentifyTrayApplication(identifier, id) {
    Run, komorebic.exe identify-tray-application %identifier% "%id%", , Hide
}

IdentifyLayeredApplication(identifier, id) {
    Run, komorebic.exe identify-layered-application %identifier% "%id%", , Hide
}

IdentifyBorderOverflowApplication(identifier, id) {
    Run, komorebic.exe identify-border-overflow-application %identifier% "%id%", , Hide
}

FocusFollowsMouse(boolean_state, implementation) {
    Run, komorebic.exe focus-follows-mouse %boolean_state% --implementation %implementation%, , Hide
}

ToggleFocusFollowsMouse(implementation) {
    Run, komorebic.exe toggle-focus-follows-mouse  --implementation %implementation%, , Hide
}

MouseFollowsFocus(boolean_state) {
    Run, komorebic.exe mouse-follows-focus %boolean_state%, , Hide
}

ToggleMouseFollowsFocus() {
    Run, komorebic.exe toggle-mouse-follows-focus, , Hide
}

AhkLibrary() {
    Run, komorebic.exe ahk-library, , Hide
}

AhkAppSpecificConfiguration(path, override_path) {
    Run, komorebic.exe ahk-app-specific-configuration %path% %override_path%, , Hide
}

FormatAppSpecificConfiguration(path) {
    Run, komorebic.exe format-app-specific-configuration %path%, , Hide
}

NotificationSchema() {
    Run, komorebic.exe notification-schema, , Hide
}

; Resets
Stop()
Start("")


; ueli
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "ueli.exe", , Hide
Run, komorebic.exe float-rule exe "ueli.exe", , Hide

; Default to minimizing windows when switching workspaces
WindowHidingBehaviour ("minimize")

; Enable hot reloading of changes to this file
WatchConfiguration ("enable")

; Ensure there are 5 workspaces created on monitor 0
EnsureWorkspaces(0, 5)

; Configure the invisible border dimensions
InvisibleBorders(7, 0, 14, 7)

; Configure the 1st workspace
WorkspaceName(0, 0, "main")

; Configure the 2nd workspace
WorkspaceName(0, 1, "columns") ; Optionally set the name of the workspace
WorkspacePadding(0, 1, 30) ; Set the padding around the edge of the screen
ContainerPadding(0, 1, 30) ; Set the padding between the containers on the screen
WorkspaceRule("exe", "slack.exe", 0, 1) ; Always show chat apps on this workspace

; Configure the 3rd workspace
WorkspaceName(0, 2, "thicc")
WorkspacePadding(0, 2, 200) ; Set some super thicc padding

; Configure the 4th workspace
WorkspaceName(0, 3, "matrix")
WorkspacePadding(0, 3, 0) ; No padding at all
ContainerPadding(0, 3, 0) ; Matrix-y hacker vibes

; Configure the 5th workspace
WorkspaceName(0, 4, "floaty")
WorkspaceTiling(0, 4, "disable") ; Everything floats here

; Configure floating rules
FloatRule("class", "SunAwtDialog") ; All the IntelliJ popups


; Generated by komorebic.exe
; To use this file, add the line below to the top of your komorebi.ahk configuration file
; #Include %A_ScriptDir%\komorebi.generated.ahk


; AutoHotkey
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "AutoHotkeyU63.exe", , Hide
Run, komorebic.exe float-rule title "Window Spy", , Hide


; Calculator
Run, komorebic.exe float-rule title "Calculator", , Hide


; Cron
Run, komorebic.exe identify-border-overflow-application exe "Cron.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "Cron.exe", , Hide

; Discord
Run, komorebic.exe identify-border-overflow-application exe "Discord.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "Discord.exe", , Hide

; DiscordCanary
Run, komorebic.exe identify-border-overflow-application exe "DiscordCanary.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "DiscordCanary.exe", , Hide

; DiscordDevelopment
Run, komorebic.exe identify-border-overflow-application exe "DiscordDeveloper.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "DiscordDeveloper.exe", , Hide

; DiscordPTB
Run, komorebic.exe identify-border-overflow-application exe "DiscordPTB.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "DiscordPTB.exe", , Hide

; GOG Galaxy
Run, komorebic.exe identify-border-overflow-application exe "GalaxyClient.exe", , Hide
Run, komorebic.exe manage-rule exe "GalaxyClient.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "GalaxyClient.exe", , Hide
; Targets a hidden window spawned by GOG Galaxy
Run, komorebic.exe float-rule class "Chrome_RenderWidgetHostHWND", , Hide


; IntelliJ IDEA
Run, komorebic.exe identify-object-name-change-application exe "idea63.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "idea63.exe", , Hide
; Targets JetBrains IDE popups and floating windows
Run, komorebic.exe float-rule class "SunAwtDialog", , Hide

; Logi Bolt
Run, komorebic.exe float-rule exe "LogiBolt.exe", , Hide

; LogiTune
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "LogiTune.exe", , Hide
Run, komorebic.exe float-rule exe "LogiTune.exe", , Hide

; Logitech G HUB
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "lghub.exe", , Hide
Run, komorebic.exe identify-border-overflow-application exe "lghub.exe", , Hide

; Logitech Options
Run, komorebic.exe float-rule exe "LogiOptionsUI.exe", , Hide

; Mica For Everyone

; Microsoft Excel
Run, komorebic.exe identify-border-overflow-application exe "EXCEL.EXE", , Hide
Run, komorebic.exe identify-layered-application exe "EXCEL.EXE", , Hide
; Targets a hidden window spawned by Microsoft Office applications
Run, komorebic.exe float-rule class "_WwB", , Hide

; Microsoft Outlook
Run, komorebic.exe identify-border-overflow-application exe "OUTLOOK.EXE", , Hide
Run, komorebic.exe identify-layered-application exe "OUTLOOK.EXE", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "OUTLOOK.EXE", , Hide

; Microsoft PowerPoint
Run, komorebic.exe identify-border-overflow-application exe "POWERPNT.EXE", , Hide
Run, komorebic.exe identify-layered-application exe "POWERPNT.EXE", , Hide

; Microsoft Teams
; Target Teams pop-up notification windows
Run, komorebic.exe float-rule title "Microsoft Teams Notifications", , Hide

; Microsoft Word
Run, komorebic.exe identify-border-overflow-application exe "WINWORD.EXE", , Hide
Run, komorebic.exe identify-layered-application exe "WINWORD.EXE", , Hide

; Modern Flyouts
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "ModernFlyoutsHost.exe", , Hide

; Mozilla Firefox
Run, komorebic.exe identify-object-name-change-application exe "firefox.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "firefox.exe", , Hide
; Targets invisible windows spawned by Firefox to show tab previews in the taskbar
Run, komorebic.exe float-rule class "MozillaTaskbarPreviewClass", , Hide

; NiceHash Miner
Run, komorebic.exe identify-border-overflow-application exe "nhm_app.exe", , Hide
Run, komorebic.exe manage-rule exe "nhm_app.exe", , Hide

; Obsidian
Run, komorebic.exe identify-border-overflow-application exe "Obsidian.exe", , Hide
Run, komorebic.exe manage-rule exe "Obsidian.exe", , Hide

; Paradox Launcher
Run, komorebic.exe float-rule exe "Paradox Launcher.exe", , Hide

; PyCharm
Run, komorebic.exe identify-object-name-change-application exe "pycharm63.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "pycharm63.exe", , Hide

; QuickLook
Run, komorebic.exe float-rule exe "QuickLook.exe", , Hide

; RoundedTB
Run, komorebic.exe identify-border-overflow-application exe "RoundedTB.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "RoundedTB.exe", , Hide

; ShareX
Run, komorebic.exe identify-border-overflow-application exe "ShareX.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "ShareX.exe", , Hide

; Signal
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "signal.exe", , Hide

; Slack
Run, komorebic.exe identify-border-overflow-application exe "slack.exe", , Hide
Run, komorebic.exe manage-rule exe "slack.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "slack.exe", , Hide

; Spotify
Run, komorebic.exe identify-border-overflow-application exe "Spotify.exe", , Hide
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "Spotify.exe", , Hide

; Steam
Run, komorebic.exe identify-border-overflow-application class "vguiPopupWindow", , Hide

; TouchCursor
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "tcconfig.exe", , Hide
Run, komorebic.exe float-rule exe "tcconfig.exe", , Hide

; TranslucentTB
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "TranslucentTB.exe", , Hide

; Visual Studio Code
Run, komorebic.exe identify-border-overflow-application exe "Code.exe", , Hide

; Windows Explorer
; Targets copy/move operation windows
Run, komorebic.exe float-rule class "OperationStatusWindow", , Hide
Run, komorebic.exe float-rule title "Control Panel", , Hide

; Wox
; Targets a hidden window spawned by Wox
Run, komorebic.exe float-rule title "Hotkey sink", , Hide

; Zoom
Run, komorebic.exe float-rule exe "Zoom.exe", , Hide

; qBittorrent
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "qbittorrent.exe", , Hide

; ueli
; If you have disabled minimize/close to tray for this application, you can delete/comment out the next line
Run, komorebic.exe identify-tray-application exe "ueli.exe", , Hide
Run, komorebic.exe float-rule exe "ueli.exe", , Hide


; Identify Minimize-to-Tray Applications
IdentifyTrayApplication("exe", "Discord.exe")
IdentifyTrayApplication("exe", "Spotify.exe")
IdentifyTrayApplication("exe", "GalaxyClient.exe")

; Identify Electron applications with overflowing borders
IdentifyBorderOverflowApplication("exe", "Discord.exe")
IdentifyBorderOverflowApplication("exe", "Spotify.exe")
IdentifyBorderOverflowApplication("exe", "GalaxyClient.exe")
IdentifyBorderOverflowApplication("class", "ZPFTEWndClass")

; Identify applications to be forcibly managed
ManageRule("exe", "GalaxyClient.exe")

; Custom Rules
ToggleMouseFollowsFocus()
WorkspaceCustomLayout(0,0, "C:\WORKING\tools\komorebi\config\layout.json")


; Change the focused window, Alt + Vim direction keys
!h::
Focus("left")
return

!j::
Focus("down")
return

!k::
Focus("up")
return

!l::
Focus("right")
return

; Move the focused window in a given direction, Alt + Shift + Vim direction keys
!+h::
Move("left")
return

!+j::
Move("down")
return

!+k::
Move("up")
return

!+l::
Move("right")
return

; Stack the focused window in a given direction, Alt + Shift + direction keys
!+Left::
Stack("left")
return

!+Down::
Stack("down")
return

!+Up::
Stack("up")
return

!+Right::
Stack("right")
return

!]::
CycleStack("next")
return

![::
CycleStack("previous")
return

; Unstack the focused window, Alt + Shift + D
!+d::
Unstack()
return

; Promote the focused window to the top of the tree, Alt + Shift + Enter
!+Enter::
Promote()
return

; Manage the focused window
!=::
Manage()
return

; Unmanage the focused window
!-::
Unmanage()
return

; Switch to an equal-width, max-height column layout on the main workspace, Alt + Shift + C
!+c::
ChangeLayout("columns")
return

; Switch to the default bsp tiling layout on the main workspace, Alt + Shift + T
!+t::
WorkspaceCustomLayout(0,0, "C:\WORKING\tools\komorebi\config\layout.json")
LoadCustomLayout("C:\WORKING\tools\komorebi\config\layout.json")
return

!+y::
WorkspaceCustomLayout(0,0, "C:\WORKING\tools\komorebi\config\layout-mobile.json")
LoadCustomLayout("C:\WORKING\tools\komorebi\config\layout-mobile.json")
return

; Toggle the Monocle layout for the focused window, Alt + Shift + F
!+f::
ToggleMonocle()
return

; Toggle native maximize for the focused window, Alt + Shift + =
!+=::
ToggleMaximize()
return

; Flip horizontally, Alt + X
!x::
FlipLayout("horizontal")
return

; Flip vertically, Alt + Y
!y::
FlipLayout("vertical")
return

; Force a retile if things get janky, Alt + Shift + R
!+r::
Retile()
return

; Float the focused window, Alt + T
!t::
ToggleFloat()
return

; Reload ~/komorebi.ahk, Alt + O
!o::
ReloadConfiguration()
return

; Pause responding to any window events or komorebic commands, Alt + P
!p::
TogglePause()
return

; Enable focus follows mouse
!0::
ToggleFocusFollowsMouse("komorebi")
return

; Switch to workspace
!1::
Send !
FocusWorkspace(0)
return

!2::
Send !
FocusWorkspace(1)
return

!3::
Send !
FocusWorkspace(2)
return

!4::
Send !
FocusWorkspace(3)
return

!5::
Send !
FocusWorkspace(4)
return

; Move window to workspace
!+1::
MoveToWorkspace(0)
return

!+2::
MoveToWorkspace(1)
return

!+3::
MoveToWorkspace(2)
return

!+4::
MoveToWorkspace(3)
return

!+5::
MoveToWorkspace(4)
return